name: ShellCheck
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@0.5.0
        with:
          severity: "info"
          check_together: true
          ignore: "./LINUXexplo.sh"
        env:
          SHELLCHECK_OPTS: -e SC2086 -e SC1061 -e SC1072 -e SC2059
        
